name: Pickle Stability Test
on: [push, pull_request]
jobs:
  test-pickle-hash:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy   # Add any other packages you need here
    
    - name: Run pickle hash tests
      run: python main.py --run
      timeout-minutes: 5
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: pickle-hash-results-${{ matrix.os }}-py${{ matrix.python-version }}
        path: |
          pickle_hash_results_*.json
          results_*.json
      if: always()

  compare-results:
    needs: test-pickle-hash
    runs-on: ubuntu-latest
    if: always() 
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy   # Also install dependencies for the comparison job
    
    - name: Download all test results
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: List downloaded artifacts
      run: |
        find artifacts -type f -name "*.json" | sort
      
    - name: Combine results
      run: |
        mkdir -p combined_results
        find artifacts -name "*.json" -exec cp {} combined_results/ \;
        ls -la combined_results/
        
    - name: Compare results
      run: |
        cd combined_results
        python ../main.py --compare
